# For parameter descriptions, please refer to the template parameter files for each node.

# Map ekf, odom
ekf_filter_node_odom_local:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    # map_frame: map  # map
    odom_frame: odom
    base_link_frame: base_link  # base_footprint # the frame id used by the robot's diff drive plugin
    world_frame: odom

    odom0: /a200_0309/platform/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # imu0: oakd/imu
    # imu0_config: [false, false, false, # X, Y, Z
    #               false, false, true,   # roll, pitch, yaw
    #               false, false, false, # linear velocities (X, Y, Z)
    #               false, false, true,   # angular velocities (roll, pitch, yaw)
    #               false, false, false] # linear accelearations (X, Y, Z)

    # imu0_remove_gravitational_acceleration: true


# World ekf, gnss
ekf_filter_node_map_global:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link # the frame id used by the robot's diff drive plugin
    world_frame: map

    odom0: /a200_0309/platform/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    odom1: odometry/gps
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    odom2: gps/odom
    odom2_config: [false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # imu0: oakd/imu
    # imu0_config: [false, false, false, # X, Y, Z
    #               false, false, true,   # roll, pitch, yaw
    #               false, false, false, # linear velocities (X, Y, Z)
    #               false, false, true,   # angular velocities (roll, pitch, yaw)
    #               false, false, false] # linear accelearations (X, Y, Z)

    # imu0_remove_gravitational_acceleration: true


navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.1237
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false