# For parameter descriptions, please refer to the template parameter files for each node.

# Map ekf, odom
ekf_filter_node_odom_local:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    # map_frame: map  # map
    odom_frame: odom
    base_link_frame: UGV_link  # base_footprint # the frame id used by the robot's diff drive plugin
    world_frame: odom

    odom0: odometry/wheel
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    imu0: oakd/imu
    imu0_config: [false, false, false, # X, Y, Z
                  false, false, true,   # roll, pitch, yaw
                  false, false, false, # linear velocities (X, Y, Z)
                  false, false, true,   # angular velocities (roll, pitch, yaw)
                  false, false, false] # linear accelearations (X, Y, Z)

    imu0_remove_gravitational_acceleration: true
    
    # imu1: livox/imu/data
    # imu1_config: [false, false, false,
    #               false, false, false,
    #               false, false, false,
    #               true, true, true,
    #               true, true, true]

    # imu1_remove_gravitational_acceleration: true


# World ekf, gnss
ekf_filter_node_map_global:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: UGV_link # the frame id used by the robot's diff drive plugin
    world_frame: map

    odom0: odometry/wheel
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    odom1: odometry/gps
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    imu0: oakd/imu
    imu0_config: [false, false, false, # X, Y, Z
                  false, false, false,   # roll, pitch, yaw
                  false, false, false, # linear velocities (X, Y, Z)
                  false, false, true,   # angular velocities (roll, pitch, yaw)
                  false, false, false] # linear accelearations (X, Y, Z)

    imu1: gps/heading/imu
    imu1_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    # imu1: livox/imu/data
    # imu1_config: [false, false, false,
    #               false, false, false,
    #               false, false, false,
    #               true, true, true,
    #               true, true, true]

    # imu1_remove_gravitational_acceleration: true


navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.1237  # True for Västerås, Sweden. Please update if running in another locale.
    yaw_offset: 1.5707963
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
