services:
  ros:
    image: slarc/dev:latest
    container_name: slarc_dev
    build:
      context: .
      args:
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
        - USER_NAME=$USER
        - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ../ros_ws/:/slarc_ws/:rw
      - ../third_party_sdk_drivers:/third_party_sdk_drivers:rw
      - ../foxglove_extensions/:/foxglove_extensions/:rw
      - /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      - /dev:/dev:rw
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
