launch_options:
  ros__parameters:
    namespace: "seeker"
    model: "Rig5"
    use_JSP: false
    use_simtime: false
    nav2_config: ""
    navsat_config: ""
    livox_config: ""
    ardu_config: ""
    camera_config: ""
    camera_serever_config: ""
