oak_cameras:
  "1944301081DB714800":
    name: oak0
    params:
      camera:
        i_mx_id: "1944301081DB714800"
        i_enable_imu: true
        i_enable_ir: false
        i_pipeline_type: RGBD
        i_usb_speed: SUPER_PLUS
        i_nn_type: none
      nn:
        enable: false
      spatial_detection:
        enable: false

      imu:
        i_enable_rotation: true
        i_rot_mode: ROTATION_VECTOR
        i_rot_freq: 400

      rgb:
        i_board_socket_id: 0
        i_fps: 30.0
        i_height: 720
        i_width: 1280
        i_resolution: "1080P"
        i_publish_topic: true

      stereo: {}   # required, even if empty

      oak0:
        rgb:
          image_raw:
            enable_pub_plugins: 
              - image_transport/raw

        stereo:
          image_raw:
            enable_pub_plugins: 
              - image_transport/raw
      use_sim_time: false


  "19443010B1627E4800":
    name: oak2
    params:
      camera:
        i_mx_id: "19443010B1627E4800"
        i_enable_imu: true
        i_enable_ir: false
        i_pipeline_type: RGBD
        i_usb_speed: SUPER_PLUS
        i_nn_type: none
      nn:
        enable: false
      spatial_detection:
        enable: false

      imu:
        i_enable_rotation: true
        i_rot_mode: ROTATION_VECTOR
        i_rot_freq: 400

      rgb:
        i_board_socket_id: 0
        i_fps: 30.0
        i_height: 720
        i_width: 1280
        i_resolution: "1080P"
        i_publish_topic: true

      stereo: {}

      oak2:
        rgb:
          image_raw:
            enable_pub_plugins: 
              - image_transport/raw
        stereo:
          image_raw:
            enable_pub_plugins: 
              - image_transport/raw


usb_cameras:
  "2450ZB1354S8":
    name: camera0
    params:
      image_width: 640
      image_height: 480
      pixel_format: mjpeg2rgb
      framerate: 24.0

      # disable compressed transports
      image_transport: raw


